apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgC9BCY9Q6qjgJKQQl+XJGaEL+bLammiwAXAu6GEGCnrrRlWszUShoDcKKqc0eQ3fq1o6Hvgvv+knbUSY3qojrUxvPd/043PJ1Wy+qmAnsL2PEay9eGQ2huhRwV8A0SzfjlTSrkecjL4PeIDoXfKdmjK6Q5cbXcdlwiZwatPO/Z3dUE9e43WkARApQyipZGrkPNYBmUSIRvREjCbg9VHsKHxOw2XnEsfS+uxiZLL2XXhCGgvPV4np2RROH0pCpC8OrHVxt72f8+S9FAidV3l/iMMCoLpINGL82dhHGydUM0lnJ6av2esWIVtmGkETjSeKgCU1B8G5Mz5gzEofm6jQAlxehtHpMhNn6xNE10ZY/0kI9t7/9dqzFPb8DOQXCXj0xJGhV3xmNJOSWxxtwJeUrnSC8zMi39+gl/Mp/WBg0IayQS47TozBWb2bI2dxmaEwqi5+6h5sfmS2GEODn3ryyXiP4KUZ7itX6DrYbaLSrWIlRTbnb8Vf11Dk/6OhAPhLvP9Klq/j0bH7Pnwf9jNeCuk4qzDqOlRtlIe/SyS89ORHL77AxXJn7t4F8VxCNEbWp74SQUXU5vvIimBbZTMevb9OsOfZ9Y1/Uaha3cu5IZwwIti8EJ2FsNQ+xd6qMekbD6VWVFPsh7vrfrws2eEeUQvMpugkpx9+jwvo43Np5KhF3BhNKDv9oIlySiQE+z7oHrs/wz7hEinzL6ToXYOSqvQS1AoJdsyi+A6No5cSC4I7IYIuvVQRjb+
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

