apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCa/gwLhGw4KITX5z8i1YDizcInk2jnX7andr6cNBJVl/KUjMvOedyj3vV1iTuPx7UzSrksrAj3V/AFVkOykU8CuGynkGuJPFzMxFczuxsYlq6mkgLJSXZZqtWu0BhRwGA0EKegJkttUdWaBe4lVAp4x90fu+EFe6Pu6tl9xRB/j3FymDQhNcMFMEiILcxVIrwnz9V/2mf3FN6F2B0+qgvNA92Y7AYCQwEtTj6vPo6Kse1nDeqk8uLgVu9eeFZsLFYUAegDFPSTYRZjchxjXgy62WNCG1BdjKGJKbmx9siS7jQDue0K92rqI4nmUrMMknEDmUD1BnjM1B50if76rQftNsQ+DOjZ0PnSuFv5f1cXDMGaccNS1jSa39yzpHOK/M412t1OmMPT9nYhUHorPdPDrhznQsAzK7BfRLWHvRNtgApWJMjVUPmxZQ832UBe7wejZGW61gvo9o27PML7nY0Zix1tD3R/6ZpQgVqoK2lgzYD8RwumlBtnwaNa0pGyVft06OlaCmO7dk6g1jxuSqALf/YfUCRXoR5BJeWJxSKl6pptw36MwaydQBUlL7yBjKeHxfwk1RFSXBp0qwyGVqzbySuyuA6aiSyiII0zttsCI1P5puH/e0FkZH8T3NZ4J+FGLDCB0tLP3qX4AGE2vNoG4SOWURmY3+bOquvuc8fFWdNDsakbTq2KrggL/vjLaqOCcMbeGJkvqrtIuU37j3yimHeYRPiXo18EvN7LmQ9qEX/MpEBYbnLF
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

