apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgB9FS9JFLKfYI+lG5I81RfOEiazLb1sAIlSQGzjASfptMCwjLAaFc60ugOWD4oSAiwtgtRosbejCMghx+Om0+SniL0QRz53aD+ekonIbQ03G/Hv7o62UmQ3Y6X9+npMpYx6iL9qjxO/FRGhx84TuokXFLNxP9pxmh8FW9CbmEC/AS4wa0dxdBo2XJJM17jea6Jdy0JnjtRUamqDCBzpBzfrWyQ1+MKm0LKhekg3R+z3ojXXoNmBfaj7w4lRLqzLPvk5Xzmhyu2hFzzi3K9hIpC8UB7Y3hiq0RXtirNQ/k3jKThf0AM0iqhLGEuRa5bdxtflwci7nlRzPi9XbbEk+fXMztN+eNDdka52y9/Tp4WNL35nMe9IP1lYoIaDKG4LZuX0TmTigWKaUezY7CMe7UqUrleQT5Bw4hHrt+eE+30k2SvlOyc/4Tdpbk9fHP5hvGGe8y6kGMyxYOKPSI63rSNJVRBVNik6pQekdZ6x1ij8vRND5s0VjF/sKZJuoZrl6RsEeWfEAZZO34VE+f0py8FuZsUjrV6S2zCsk3n0QhAd9aHH/B0lRK50OoyMp0IRwxnfyWHMqlXMrotHPUtux/s7BgiySUstgsa8p83PgPARMuE76ziLTQ0pLLxiO94FsXPG6lThUgYo49Lw5Y+meq0nr1cDmFmUCRUJF6+Vk0Tr+UzIMgb4m9bIrBL6bKNbwuY5eTgKHcNnraQ2YyLYQorHNe/9i9cJFbz/nUnZqh0NiQfe5eTMl8L7
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

