apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCjuab+svVkbERW0tU8Xdbe7p5rAGMJboSzpkY00JbWdV/6a7fJ9hAqiGQaKCDKhRX2uX1voqa7KnVQv9Veqw17yJJgZuNgzTrkEZsaWIYYHhg0a4YD9vS4kb4g7OYP0201GaJ0hcon7Tvgt4g+rdmLEHDd45fzZ7DJcx/XTTA0UIN548axmZwlw2fdpEqUe+SR7uF/3fXUgp+rRQSjffHuvsQmMLd5juPnDW+vZAzk/4xdx9xqlEQGiIHi/337EsNxWn6fc9CGn1pwThXf0+cMUKoKPzuR3ip6mCQI+qcYA8iyHb4WdLYxZ2AbI/oZciEo69/hOo9mXpNtaA/z3oCTfCzV7I5vQBwGZ9G+Tg8ha6qBO3QmzZibH2wnZsMiMM1T81y0Ja9+Tg8zCbTFhMQtBSrMjflFWIVtr+8OM7FQQ3IeOzgBvf4nc29aja7lMyeEBeu5gIYLk8rcLDpYIcyz7HqeeI+LrW+FfHTn1ediH2wS2QfSYdqpzoyMQIHM079fVv1lVaSK2OhHyxfqZUggN8Bi+iINvRLZkyqCq0FsPVDYA6+GtYIr0bmSJnBkIEgyRMgR5twOBURcsmTxC2FmzL/YHFzweBugSPGCUyoLT9sVN8sxJ2UOTx24VEDZIpludmgdQhaO37yA8wS7bxcbtUwUfQ+ATq0vzeyGjYZP0RXnQpTy03UEtsnOmvjd8tPsFV1rXlUsNjuHBNiTI3XUN98ERYX6jv7p8uCIbdQUTsAjX2Gb8c41
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

