apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgA3Gumcvn/ggaRhEiPE4zTTswBoeiH16hoOR9RdtOQPfjDSNfLY4KHRRtIRXFoE611LuDOLkPvczyU/HE+0rtFJJmQyaAvV0FRiS3ELGzAh69izAhk3TpbmYQtl8vrl3igdbedRoermMgvuNeXvScJJ9ItfFSRSSMvrfGljNM+tYD6hY96YF7ZTHuZaGwo6FpjmYTCfcnUM9Kz0oB6dyUJgGzx0oL/cyP/7AJcdwUuaXFvrMgazKKh8SwDwQMZht61O5KmRq1dkZ4dyTHVDXoQPklhFhfp0tYDfs+Qe26v3cVYcfzOMVpgU45wQy8SX8SGHqJCeqkx0dEV6MLug9eXTye0WWhXuAMSEvaAsRz7rsa0gfZjQHEbN8HM5RPLKrCdL0l8N02D7OedQcfd46tZa6oNlrVhounnfvdYjGWh9KeJQK5moNgqtGbxQgZR+fNXUajfQJdThkch1qbbMLyDXAb6SkCc2aTN3XaZRorDWBOEgYoAAiqP2x0rA+E5a/HlF5PyKH+Gbp9achwhyyxyCYyuxgGANZGDjPIqhn3R6Tcc1clrMyY4I4aOX4GuxH9bO7Yff5yQ2l4xAn4N73FrJIM+hjw6vl/BoHzceeJOhGUrCtMcyjAJJuxlafvrnGGg/s6icF06KaG3CbrahI7iGzKc/ETLSK/4a2ceBgz+SbuG8/DUS2EELr8jls5hUrRpaZKGVNR/IUpk/uL3pQXrzi3JKZ0p2R/esw99To0z9+gmnKRqQyVIK
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

